### ISSUE TITLE
You should not version your venv

### ISSUE THREAD

**Issue by JulienPalard** [ritvikjain99/IMGSched#1]
Hi, sorry to be a bit intrusive, I spotted your repo while working on an unrelated bot ...

Just to say you should not version your venv directory, it's too big and it's too easy to rebuild, just version a "requirements.txt" containing the list of packages you depend on.

**Comment by vegeta999** [comment]
That's so good of you, thanks for your suggestion, actually I am a newbie and your remark would surely be add to my learning.

**Comment by JulienPalard** [comment]
Don't worry, we've all been newbies once. Welcome to Python!

I'll close this issue just to avoid having hundreds of open issues. Hey while I'm here, I'm one of the creators of https://hackinscience.org, a Python exercises platform (free and open source).

If you have any questions about versionning or not a venv, feel free to ask I think I'll receive a notification and I'll gladly answer.

Bests!
